name: Cypress E2E Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs tests for every PR to 'main'
  schedule:
    - cron: "0 12 * * 1-5"  # Runs tests Monday to Friday at noon (UTC)

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Faster & ensures dependencies match package-lock.json

      - name: Ensure results directory exists
        run: mkdir -p cypress/results  # Avoid "no files found" error

      - name: Run Cypress tests (Production)
        run: npx cross-env ENV=prod npm run test:ci

      - name: Run Cypress tests (Development)
        run: npx cross-env ENV=dev npm run test:ci

      - name: Upload test results (if using mochawesome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results
