name: Cypress E2E Tests

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs tests for every PR to 'main'
  schedule:
    - cron: "0 12 * * 1-5"  # Runs tests Monday to Friday at noon (UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [prod, dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (${{ matrix.environment }})
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          record: false
        env:
          ENV: ${{ matrix.environment }}
          # Add any other environment-specific variables here
          CYPRESS_BASE_URL: ${{ matrix.environment == 'prod' && 'https://www.saucedemo.com' || 'https://dev.saucedemo.com' }}

      - name: Generate test report
        if: always()
        run: npx mochawesome-merge cypress/reports/**/*.json > cypress/reports/full-report.json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.environment }}
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
          retention-days: 30

      - name: Upload bug reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bug-reports
          path: docs/bug-reports.csv
          retention-days: 30
